use dist_saludable;
insert into categories (id,name) values 
(1,'Sin T.A.C.C.'),
(2,'Aceites'),
(3,'Cereales'),
(4,'Kiosko'),
(5,'Infusiones'),
(6,'Frutas'),
(7,'Frutos secos'),
(8,'Disecados'),
(9,'Legumbres'),
(10,'Endulzantes'),
(11,'Suplementos'),
(12,'Vegano'),
(13,'Semillas'),
(14,'Leches'),
(15,'Infusiones'),
(16,'Yerba'),
(17,'Untables'),
(18,'Harinas'),
(19,'Fideos'),
(20,'Galletitas'),
(21,'jugos'),
(22,'Panificados'),
(23,'Sal'),
(24,'Condimentos'),
(25,'Mix');