//This script hashes all passwords generated by Mokaroo y saves them into a new file
const path = require('path'),
      fs = require('fs'),
      bcrypt = require('bcryptjs'),
      hash = bcrypt.genSaltSync(10)
      ;
 
function hashPasswords(url){
    let data = fs.readFileSync(path.join(__dirname,url),'utf-8');
    let users = JSON.parse(data);
    for(let user of users){
        let newPassword = bcrypt.hashSync(user.password,hash);
        user.password = newPassword;
    }
    fs.writeFileSync(
        path.join(__dirname,'users.json'),
        JSON.stringify(users,null,2)
        );
}
// hashPasswords('users1.json');

//this function generates a .sql script that populates users table from database
function generateScript(){
    let data = fs.readFileSync(path.join(__dirname,'users.json'),'utf-8');
    let users = JSON.parse(data);
    let query = "use dist_saludable;\ninsert into users (first_name,last_name,email,password) values \n";
    for(let user of users){
        query +=`('${user.first_name}','${user.last_name}','${user.email}','${user.password}'),\n`
    }
    fs.writeFileSync(
        path.join(__dirname,'add_users.sql'),
        query
        );
}
generateScript();


